branches:
  only:
    - main
language: python
python:
  - "3.9"
install:
  - curl -sSL https://install.python-poetry.org | python3 - --version 1.1.11
  - poetry env use system
  - poetry install --dev
script:
  - pytest
  - poetry build