version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.9
        commands:
            - curl -sSL https://install.python-poetry.org | python3 - --version 1.1.11
            - export PATH=/root/.local/bin:$PATH
            - poetry env use system
            - poetry install
            - poetry version $(poetry version -s).$CODEBUILD_BUILD_NUMBER
    pre_build:
        commands:
            - echo "testing nothing ..."
            #- poetry run pytest
    build:
        commands:
            - poetry build
    post_build:
        commands:
            - echo "we are in the post build phase"
            - poetry version

