version: 0.2

phases:
    install:
        runtime-versions:
            python: 3.9
        commands:
            - aws s3 cp s3://stdiff/dvc/binary/dvc_2.8.3_amd64.deb /tmp/dvc_2.8.3_amd64.deb
            - dpkg -i /tmp/dvc_2.8.3_amd64.deb
            - dvc pull
            - curl -sSL https://install.python-poetry.org | python3 - --version 1.1.11
            - export PATH=/root/.local/bin:$PATH
            - poetry env use system
            - poetry install
            - export VERSION=$(poetry version -s).$CODEBUILD_BUILD_NUMBER
            - poetry version $VERSION
    pre_build:
        commands:
            - poetry run black --check */*.py */*/*.py
            - dvc repro
            - poetry run pytest
    build:
        commands:
            - poetry build
            - docker build --build-arg VERSION=$VERSION -t emo-classifier:$VERSION .
            - docker tag emo-classifier:$VERSION 050266116122.dkr.ecr.eu-central-1.amazonaws.com/emo-classifier:$VERSION
    post_build:
        commands:
            - cp notebook/error_analysis.html dist/error_analysis-$VERSION.html
            - mv dist $VERSION
            - docker push 050266116122.dkr.ecr.eu-central-1.amazonaws.com/emo-classifier:$VERSION
artifacts:
    files:
        - $VERSION/emo_classifier-*-py3-none-any.whl
        - $VERSION/error_analysis-$VERSION.html
