stages:
  ingestion:
    cmd: poetry run ingestion
    outs:
      - data/train.parquet
      - data/dev.parquet
      - data/test.parquet
  train:
    cmd: poetry run train
    deps:
      - data/train.parquet
    outs:
      - emo_classifier/artifact/
    metrics:
      - emo_classifier/resources/TrainingMetrics.json
  evaluate:
    cmd: poetry run jupyter nbconvert --to HTML --execute notebook/error_analysis.ipynb
    deps:
      - data/dev.parquet
      - data/test.parquet
      - emo_classifier/artifact
    outs:
      - emo_classifier/resources/dev_predictions.parquet
      - emo_classifier/resources/Thresholds.json
      - notebook/error_analysis.html
    metrics:
      - emo_classifier/resources/DevMetrics.json
      - emo_classifier/resources/TestMetrics.json