[tool.poetry]
name = "emo-classifier"
version = "0.1.0"
description = "Just a demonstration of a PyTorch project with goemotions data set"
authors = ["Hironori Sakai <crescent.lab@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = ">=3.9,<3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
